### ISSUE TITLE
Hal for Athene

### ISSUE THREAD

**Issue by zoggn** [MotorolaMobilityLLC/motorola-external-v4l2_hal#1]
Hello, can you please give HAL for Moto g4(athene)?

**Comment by awheeler-mmi** [comment]
Hey @zoggn, I believe we have already released all the open-source code for athene.  Much of the HAL is closed-sourced, but is there a specific open-source module that you have identified as missing?

Thanks, -andrew

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
